### ISSUE TITLE
(L)uci wireless configuration conflicts

### ISSUE THREAD

**Issue by ghost** [newkit/wifischedule#1]
Hi, 
If wireless was previously configured using LuCI and set to disable when the command `wifi up` is executed, it seems wifi will not be enabled at all.
Shouldn't wifischedule 'get' the uci configuration, mostly the _'option disabled=1/0_' for wireless interface(s) and then work around that?
i.e - If option disabled (in /etc/config/wireless), set it to enabled then `wifi up`

**Comment by newkit** [comment]
I see your point, but why would expect that disabling in LUCI and Disable/Enabling through wifischeduler would be the same?

Why is it disabled at first place in LUCI? Maybe the user has a reason to do so, and would like this particular WIFI to stay disabled?

**Comment by ghost** [comment]
I know it's not the same, but users will mistakenly think that, like I did at first time, I don't see a note in readme or in LuCI app mentioning that. 

So, we need wifi not set to disabled in LuCI, in case of a power outage, router will boot with wifi enabled until the cron job to disable wifi kicks on, could be hours, think about it.
e.g - I want wifi enabled between 10AM and 8PM, power goes out at 12AM and comes back on, wifi will be enabled all night...
This bring **another problem**, the use of crontab...

At the moment I use a simple shell script to enable/disable wifi in specific time windows, because it checks every x minutes and gets the state of _/etc/config/wireless_ the problems reported above will not happen.
It's not as lightweight as your script, it needs to be always running, but actually needs very little resources.

I know it may not be what you want for your script, but I felt incredible frustrated after installing it and see that was pretty useless to me.

I just thought that you would want to have feedback about using your script in real life situations, please don't take this as an insult or an obligation to change it.

**Comment by newkit** [comment]
I really appreciate you taking the time to evaluate the code, giving feedback and sharing you thoughts and experiences. I believe that this is an aspect in order to create good and usable software. 

In regards to the outlined power failure topic - I guess it would be sufficient to check at boot up, whether WiFi should be disabled. Let me see if I can integrate that. 
I personally would not like to implement an approach where every x minutes a script runs when there is the oppertunity to use an event based system such as cron.

In regards to the enabling/disabling issue - do you think it should be mentioned in the README that those two switches are different?

**Comment by ghost** [comment]
> In regards to the outlined power failure topic - I guess it would be sufficient to check at boot up, whether WiFi should be disabled. Let me see if I can integrate that.

I think that would work okay.

> In regards to the enabling/disabling issue - do you think it should be mentioned in the README that those two switches are different?

Yes, a simple note would be nice, also a heads up that if wifi is disabled in (L)UCI configuration this script will not be able to enable wifi at all.
You could even have that in the LuCI app. just like most of them have a quick description of what the app actually does.

**Comment by newkit** [comment]
Thank you for you patience. I pushed a new wifi_schedule.sh script that should fix the reported errorneous behaviour. Would you please be so kind and try it out and see if that really fixes your issues? Just copy the wifi_scheduler.sh file to /usr/bin on your router.

https://github.com/newkit/wifischedule/blob/master/net/usr/bin/wifi_schedule.sh

**Comment by ghost** [comment]
Many thanks, that should be OK now.

I know a lot of casual users that use your script and had the problems I mentioned a lot of times, mostly ending with a wrong WIFI state when they were expecting another.

The only situation it may still prevent this from working properly is the time being wrong.
e.g. My CPE210 serves WIFI only and needs main router for WAN(/LAN) gateway, after power loss, if main router is not full boot the CPE210 will not update time until there's a internet connection and the startup script may not trigger the correct WIFI state.

But that's another problem...

I still stick to my script I mentioned before, it covers most of scenarios because it's always running and checking... it's really bad if I'm like 3km away from home and WIFI is somehow disabled!
