### ISSUE TITLE
wifischedule package in OpenWRT is outdated

### ISSUE THREAD

**Issue by bedaes** [newkit/wifischedule#4]
There was a marvelous PR (https://github.com/newkit/wifischedule/pull/2) waiting for it's debut in OpenWRT :wink:

The source included with OpenWRT is so 2016: https://github.com/openwrt/packages/tree/master/net/wifischedule

**Comment by newkit** [comment]
Well... happy birthday... the present is on it's [way](https://github.com/openwrt/packages/pull/14057) :p
