### ISSUE TITLE
Wifischedule can be circumvented by rebooting

### ISSUE THREAD

**Issue by pepa65** [newkit/wifischedule#5]
The downside of just using cronjobs to turn wifi on and off is that a reboot doesn't remember the former state of the wifi. When the wifi got turned off, kids just need to reboot the router, and it's back on again...

No easy way to fix this I think. Analysing the cron jobs on startup is not right. Having a cron job running every minute to check whether wifi should be on or off?

**Comment by newkit** [comment]
There is a startup script /etc/init.d/wifi_schedule that should process the schedules and set them accodingly after a reboot. Are you saying that this is not working?

**Comment by pepa65** [comment]
Sorry, I hadn't found that, so that is already happening then. I just went by the cron entries and realized that by itself would not be enough. Great then!

**Comment by raenye** [comment]
@newkit 
For devices without RTC, how can one make sure the `/etc/init.d/wifi_schedule` runs only after the ntp client gets the correct time?

`/etc/init.d/sysfixtime` uses RTC (if existing) and filesystem timestamps (which only change when `/etc` is modified, so most likely give the time of the last enable/disable event).
