### ISSUE TITLE
Recheck should stop after a certain number of attempts

### ISSUE THREAD

**Issue by sNiXx** [newkit/wifischedule#6]
I encountered a small issue that was raised before over at [openwrt/luci](https://github.com/openwrt/luci/issues/4829).

An example to illustrate:
The following options are set: `option forcewifidown '0'`, `option starttime '06:00'` and `option stoptime '23:00'`.
There is at least one station remaining at 23:00. The script then rechecks according to what is defined as `recheck_interval`. At 06:00, the script tries to enable WiFi, which has no effect, because it is still enabled. When the station finally disconnects after 06:00, WiFi is disabled.

Maybe to deal with this, it would be helpful to have something like `recheck_retries` to define that the script should only try x times before "giving up"? I had a brief look at the code - not being well-versed at all in shell scripts - and it seems that recheck retries until successful, no matter the circumstances?

PS: Before I forget... thanks for this helpful script!

**Comment by newkit** [comment]
Hi, thanks for your feedback. Well, not sure if `recheck_retries` is the right solution the problem. I mean if the WIFI wouldn't be disabled at 06:00 in your example above, I guess you'd be fine, no? So it sounds to me like a bug what you are describing, and looking at the code https://github.com/newkit/wifischedule/blob/71a87aa6938e677d679cdd0fa37e446240050b8f/net/usr/bin/wifi_schedule.sh#L340 shows that we create a cron entry every time we can not disable the WIFI. I think this is wrong and should happen only once, when there is no recheck entry yet.

**Comment by sNiXx** [comment]
The problem is that WiFi is disabled if the station disconnects at 09:00, for instance, because the script couldn't disable WiFi during the night. But it shouldn't do that anymore after 06:00. Some lines from the (modified) log that show this behaviour:

> Thu Mar 24 05:10:00 CET 2022 /usr/bin/wifi_schedule.sh recheck
Thu Mar 24 05:10:00 CET 2022 Station(s) <MAC1> associated on wlan0
Thu Mar 24 05:10:00 CET 2022 Could not disable wifi due to associated stations, retrying...
...
Thu Mar 24 05:50:00 CET 2022 /usr/bin/wifi_schedule.sh recheck
Thu Mar 24 05:50:00 CET 2022 Station(s) <MAC1> associated on wlan0
Thu Mar 24 05:50:00 CET 2022 Could not disable wifi due to associated stations, retrying...
Thu Mar 24 06:00:00 CET 2022 /usr/bin/wifi_schedule.sh start
Thu Mar 24 06:00:00 CET 2022 /usr/bin/wifi_schedule.sh recheck
Thu Mar 24 06:00:01 CET 2022 Station(s) <MAC1> associated on wlan0
Thu Mar 24 06:00:01 CET 2022 Could not disable wifi due to associated stations, retrying...
Thu Mar 24 06:10:00 CET 2022 /usr/bin/wifi_schedule.sh recheck
Thu Mar 24 06:10:00 CET 2022 Station(s) <MAC1> associated on wlan0
Thu Mar 24 06:10:00 CET 2022 Could not disable wifi due to associated stations, retrying...
...
Thu Mar 24 16:20:00 CET 2022 /usr/bin/wifi_schedule.sh recheck
Thu Mar 24 16:20:01 CET 2022 Station(s) <MAC1> associated on wlan0
Thu Mar 24 16:20:01 CET 2022 Could not disable wifi due to associated stations, retrying...
Thu Mar 24 16:30:00 CET 2022 /usr/bin/wifi_schedule.sh recheck
Thu Mar 24 16:30:00 CET 2022 No stations associated, disable wifi.

When looking at `disable_wifi()` and `enable_wifi()`, they both remove the recheck entry:
https://github.com/newkit/wifischedule/blob/71a87aa6938e677d679cdd0fa37e446240050b8f/net/usr/bin/wifi_schedule.sh#L297
https://github.com/newkit/wifischedule/blob/71a87aa6938e677d679cdd0fa37e446240050b8f/net/usr/bin/wifi_schedule.sh#L357
This seems plausible and what I'd expect of the script.

What I don't understand: Why doesn't `enable_wifi()` properly deal with the recheck entry? Could it have to do with the fact that cron triggers both entries at the same time (i.e. at 6:00)? The start entry removes the recheck entry and just a few milliseconds later, the recheck puts it back again? I will try to simulate the situation again with `recheck_interval` set to 11

EDIT1: Today at 6:00, both recheck and start were triggered again (obviously didn't understand how cron works...), but this time it worked as expected. There we no rechecking lines in the log. Looking a lot like a race condition to me?!

**Comment by newkit** [comment]
I think the root cause it that when finally the station disconnects and `disable_wifi()` is called, we are already out of the "disable wifi timeframe". There is no checking happening currently, if that's still what we want. I'll add that, it's clearly a bug.

**Comment by newkit** [comment]
I've pushed an update to this repo.
 @sNiXx are you able to test this as well? You help would be much appreciated.
