### ISSUE TITLE
_get_uci_value error on Turris Omnia

### ISSUE THREAD

**Issue by LionelHoudelier** [newkit/wifischedule#7]
Hello,
On my Turris Omnia
wifi_schedule stop works
wifi_schedule start does not start wifi on if the lines of enable_wifi() 
`unload_modules=$(_get_uci_value_raw ${GLOBAL}.unload_modules) || _exit 1
` is NOT commented. I had to do this to make it work.

I do not understand what does unload_modules. Sorry. but commenting this line makes the script work.
Any idea to solve that problem, if needed?

**Comment by newkit** [comment]
`${GLOBAL}.unload_modules` should be a list of the modules the wifi card uses (and which should be (un)loaded in case of wifi=off|on). In the UI there is a way to detect the modules - did that work?

**Comment by newkit** [comment]
Could you check what `wifi_schedule.sh getmodules` returns?

**Comment by LionelHoudelier** [comment]
Thanks for your answers.
Commenting this line "unload_modulles" makes the script work fine.
`root@turris:~#  wifi_schedule.sh getmodules` returns:
ath9k mac80211 ath9k_hw ath9k_common compat cfg80211 ath
